### ISSUE TITLE
How did you export the meshcat recordings as html?

### ISSUE THREAD

**Issue by rcywongaa** [cohnt/Bimanual-Web#1]
Hello, Rufus here (we spoke briefly a while back), thanks for another cool paper!

May I ask how you exported the meshcat recordings such that they can be embedded/linked on a webpage while being fully interactive?

I couldn't find much from googling and naively pressing ctrl-s on a meshcat webpage doesn't work.

Thanks again!

**Comment by cohnt** [comment]
Hey Rufus! Nice to hear from you.

You'll want to check out the [Meshcat::StaticHtml](https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_meshcat.html#a8597aabcf1a98187a23fa1db634c9308) method from Drake -- this dumps the contents of the meshcat visualization into an html file like the ones on this website.

For example, this snippet of code takes in a trajectory, plays it back on meshcat, and then saves the output of `StaticHtml` to a file.
```
def render_trajectory(meshcat, build_env, directives_file, trajectory, save=False, fname="meshcat.html"):
    builder = DiagramBuilder()

    subdiagram, plant, scene_graph = build_env(meshcat, directives_file, export_sg_input=True)
    builder.AddNamedSystem("env_diagram", subdiagram)

    to_pose = builder.AddSystem(MultibodyPositionToGeometryPose(plant))
    builder.Connect(to_pose.get_output_port(), subdiagram.GetInputPort("source_pose"))

    traj_system = builder.AddSystem(TrajectorySource(trajectory))
    builder.Connect(traj_system.get_output_port(), to_pose.get_input_port())

    diagram = builder.Build()

    meshcat_visual = diagram.GetSubsystemByName("env_diagram").GetSystems()[1]

    simulator = Simulator(diagram)
    meshcat_visual.StartRecording()
    simulator.AdvanceTo(trajectory.end_time() + 0.1)
    meshcat_visual.PublishRecording()

    if save:
        with open(os.path.join(RepoDir(), "data", fname), "w") as f:
            f.write(meshcat.StaticHtml())
```

**Comment by rcywongaa** [comment]
Ah thanks a lot!
